import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

test('teacher, class, task, student upload, replacement, file download, deletion', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'tugas-api-'));
  process.env.NODE_ENV = 'test';
  process.env.DATA_DIR = dir;
  process.env.TEACHER_EMAIL = 'teacher@example.test';
  process.env.TEACHER_PASSWORD = 'strong-test-password';
  process.env.ADMIN_SETUP_KEY = 'local-admin-test-key';
  const { app, db } = await import('../server.mjs');
  const server = app.listen(0);
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const storedFile = url => join(dir, 'files', decodeURIComponent(new URL(url).pathname.slice('/files/'.length)));
  let token;
  async function api(path, options = {}) {
    const headers = { ...(options.headers || {}) };
    if (token && !headers.Authorization) headers.Authorization = `Bearer ${token}`;
    const response = await fetch(base + path, { ...options, headers });
    const body = await response.json();
    return { status: response.status, body };
  }
  try {
    const login = await api('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'teacher@example.test', password: 'strong-test-password' }) });
    assert.equal(login.status, 200);
    token = login.body.token;
    const classroom = await api('/api/classes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'IX.1' }) });
    assert.equal(classroom.status, 201);
    const classId = classroom.body.class.id;
    await api(`/api/classes/${classId}/students`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ names: ['Siswa Uji'] }) });
    const taskForm = new FormData();
    taskForm.set('title', 'Tugas Audio');
    taskForm.set('subject', 'Bahasa');
    taskForm.set('deadline', new Date(Date.now() + 365 * 86400000).toISOString());
    taskForm.set('submission_type', 'audio');
    taskForm.set('classes', JSON.stringify([classId]));
    taskForm.set('file', new Blob(['soal'], { type: 'text/plain' }), 'soal.txt');
    const created = await api('/api/tasks', { method: 'POST', body: taskForm });
    assert.equal(created.status, 201);
    assert.match(created.body.task.task_code, /^\d{6}$/);
    assert.equal(created.body.task.classes[0].name, 'IX.1');
    const taskId = created.body.task.id;
    const publicTask = await api(`/api/tasks/code/${created.body.task.task_code}`);
    assert.equal(publicTask.body.task.title, 'Tugas Audio');
    const students = await api(`/api/tasks/code/${created.body.task.task_code}/classes/${classId}/students`);
    assert.equal(students.body.students[0].name, 'Siswa Uji');
    const submit = async content => {
      const form = new FormData();
      form.set('task_id', taskId);
      form.set('task_code', created.body.task.task_code);
      form.set('student_name', 'Siswa Uji');
      form.set('student_class', 'IX.1');
      form.set('file_0', new Blob([content], { type: 'audio/mpeg' }), 'rekaman.mp3');
      return api('/api/submissions', { method: 'POST', body: form });
    };
    const first = await submit('audio-first');
    assert.equal(first.status, 201);
    assert.equal(first.body.replaced, false);
    assert.match(decodeURIComponent(first.body.file_urls[0]), /\/submissions\/[^/]+\/IX\.1\/Tepat Waktu\//);
    assert.equal(existsSync(storedFile(first.body.file_urls[0])), true);
    const replacement = await submit('audio-second');
    assert.equal(replacement.body.replaced, true);
    assert.equal(existsSync(storedFile(first.body.file_urls[0])), false);
    assert.equal(existsSync(storedFile(replacement.body.file_urls[0])), true);
    const listed = await api(`/api/tasks/${taskId}/submissions`);
    assert.equal(listed.body.submissions.length, 1);
    const file = await fetch(base + `/api/files/blob?url=${encodeURIComponent(replacement.body.file_urls[0])}`, { headers: { Authorization: `Bearer ${token}` } });
    assert.equal(await file.text(), 'audio-second');
    const usage = await api('/api/storage/usage');
    assert.ok(usage.body.used_bytes > 0);
    assert.equal((await api('/api/admin/teachers', { headers: { 'X-Admin-Key': 'wrong-key' } })).status, 401);
    const adminHeaders = { 'X-Admin-Key': 'local-admin-test-key' };
    const addedTeacher = await api('/api/admin/teachers', { method: 'POST', headers: { ...adminHeaders, 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'second@example.test', password: 'another-test-password' }) });
    assert.equal(addedTeacher.status, 201);
    assert.equal((await api('/api/admin/teachers', { headers: adminHeaders })).body.teachers.length, 2);
    const secondLogin = await api('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'second@example.test', password: 'another-test-password' }) });
    const secondAuth = { Authorization: `Bearer ${secondLogin.body.token}` };
    assert.equal((await api(`/api/tasks/${taskId}`, { headers: secondAuth })).status, 404);
    assert.equal((await api(`/api/files/blob?url=${encodeURIComponent(replacement.body.file_urls[0])}`, { headers: secondAuth })).status, 404);

    const imageTaskForm = new FormData();
    imageTaskForm.set('title', 'Tugas Gambar');
    imageTaskForm.set('subject', 'Bahasa');
    imageTaskForm.set('deadline', new Date(Date.now() + 365 * 86400000).toISOString());
    imageTaskForm.set('submission_type', 'image');
    const imageTask = await api('/api/tasks', { method: 'POST', body: imageTaskForm });
    const imageSubmit = async blob => {
      const form = new FormData();
      form.set('task_id', imageTask.body.task.id);
      form.set('task_code', imageTask.body.task.task_code);
      form.set('student_name', 'Siswa Gambar');
      form.set('student_class', 'Kelas Bebas');
      form.set('file_0', blob, 'foto.png');
      return api('/api/submissions', { method: 'POST', body: form });
    };
    const oversizedImage = await imageSubmit(new Blob([Buffer.alloc(50 * 1024 ** 2 + 1)], { type: 'image/png' }));
    assert.equal(oversizedImage.status, 413);
    assert.equal((await api(`/api/tasks/${imageTask.body.task.id}/submissions`)).body.submissions.length, 0);
    process.env.STORAGE_LIMIT_BYTES = String(usage.body.used_bytes + 1);
    const tinyImage = new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6LtAAAAAASUVORK5CYII=', 'base64')], { type: 'image/png' });
    assert.equal((await imageSubmit(tinyImage)).status, 413);
    delete process.env.STORAGE_LIMIT_BYTES;
    assert.equal((await imageSubmit(tinyImage)).status, 201);
    const fullUsage = (await api('/api/storage/usage')).body.used_bytes;
    process.env.STORAGE_LIMIT_BYTES = String(fullUsage);
    assert.equal((await imageSubmit(tinyImage)).status, 201);
    const attachmentTaskForm = new FormData();
    attachmentTaskForm.set('title', 'Lampiran Melebihi Kuota');
    attachmentTaskForm.set('subject', 'Bahasa');
    attachmentTaskForm.set('deadline', new Date(Date.now() + 365 * 86400000).toISOString());
    attachmentTaskForm.set('submission_type', 'image');
    attachmentTaskForm.set('file', new Blob(['x'], { type: 'text/plain' }), 'soal.txt');
    assert.equal((await api('/api/tasks', { method: 'POST', body: attachmentTaskForm })).status, 413);
    delete process.env.STORAGE_LIMIT_BYTES;
    const lateTaskForm = new FormData();
    lateTaskForm.set('title', 'Tugas Telat');
    lateTaskForm.set('subject', 'Bahasa');
    lateTaskForm.set('deadline', '2020-01-01 00:00');
    lateTaskForm.set('submission_type', 'audio');
    lateTaskForm.set('classes', JSON.stringify([classId]));
    const lateTask = await api('/api/tasks', { method: 'POST', body: lateTaskForm });
    const lateForm = new FormData();
    lateForm.set('task_id', lateTask.body.task.id);
    lateForm.set('task_code', lateTask.body.task.task_code);
    lateForm.set('student_name', 'Siswa Uji');
    lateForm.set('student_class', 'IX.1');
    lateForm.set('file_0', new Blob(['late-audio'], { type: 'audio/mpeg' }), 'telat.mp3');
    const late = await api('/api/submissions', { method: 'POST', body: lateForm });
    assert.equal(late.status, 201);
    assert.match(decodeURIComponent(late.body.file_urls[0]), /\/submissions\/[^/]+\/IX\.1\/Terlambat\//);
    assert.equal(existsSync(storedFile(late.body.file_urls[0])), true);
    assert.equal((await api(`/api/tasks/${taskId}`, { method: 'DELETE' })).status, 200);
    assert.equal((await api(`/api/tasks/${lateTask.body.task.id}`, { method: 'DELETE' })).status, 200);
    assert.equal((await api(`/api/tasks/${imageTask.body.task.id}`, { method: 'DELETE' })).status, 200);
    assert.equal(existsSync(storedFile(replacement.body.file_urls[0])), false);
    assert.equal(existsSync(storedFile(late.body.file_urls[0])), false);
    assert.equal((await api(`/api/tasks/${taskId}`)).status, 404);
    assert.equal((await api(`/api/admin/teachers/${addedTeacher.body.teacher.id}`, { method: 'DELETE', headers: adminHeaders })).status, 200);
    assert.equal((await api('/api/admin/teachers', { headers: adminHeaders })).body.teachers.length, 1);
  } finally {
    delete process.env.STORAGE_LIMIT_BYTES;
    await new Promise(resolve => server.close(resolve));
    db.close();
    rmSync(dir, { recursive: true, force: true });
  }
});
